export interface NewInvoiceType {
    bata: Number,
    closingKm: Number,
    extraHr: Number,
    extraHrCharges: Number,
    extraKm: Number,
    extraKmCharges: Number,
    fileAttachment: string,
    finalAmount: Number,
    invoiceDate: String,
    openingKm: Number,
    parkingCharges: Number,
    taxAmount: Number,
    tollCharges: Number,
    totalAmount: Number,
    totalKm: Number,
    tripId: Number,
    waitingChanges: Number,
}